version: '3.5'

services:
  frontend:
    container_name: money-mamagement-frontend
    build: ./source/frontend
    ports:
      - '4200:80'
    depends_on:
        - mock-server
        - backend

  backend:
    container_name: money-mamagement-backend
    build:
      context: ./source/backend
      dockerfile: Dockerfile
      args:
          ENV_TYPE: DockerCompose
    ports:
      - '5161:80'
    depends_on:
      - backend-migrations
      - backend-db

  backend-migrations:
    container_name: backend-migrations
    build:
      context: ./source/backend
      dockerfile: DockerfileMigrations
      args:
          ENV_TYPE: DockerCompose
    depends_on:
      - backend-db

  backend-db:
    container_name: backend-db
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DrOid-R2D2
