version: '2'

services:
  frontend:
    container_name: money-mamagement-frontend
    build: ./source/frontend
    ports:
      - '4200:80'

  mock-server:
    container_name: money-mamagement-mock-server
    build: ./source/mock-server
    ports:
      - '3000:${PORT}'
    environment:
      - ORIGIN=${ORIGIN}
      - PORT=${PORT}
      - AUTH_TOKEN_SECRET=${AUTH_TOKEN_SECRET}

  backend:
    container_name: money-mamagement-backend
    build: ./source/backend
    ports:
      - '9000:80'

  db:
    container_name: backend-db
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DrOid-R2D2
      POSTGRES_DB: mm-dev
