version: '2'

services:
  frontend:
    container_name: money-mamagement-frontend
    build: ./source/frontend
    ports:
      - '4200:80'

  backend:
    container_name: money-mamagement-backend
    build: ./source/mock-server
    ports:
      - '3000:${PORT}'
    environment:
      - ORIGIN=${ORIGIN}
      - PORT=${PORT}
      - AUTH_TOKEN_SECRET=${AUTH_TOKEN_SECRET}
