version: '2'

services:
  frontend:
    container_name: money-mamagement-frontend
    build: .
    ports:
      - '4200:80'

  backend:
    env_file:
      - ./mock-server/.env
    container_name: money-mamagement-backend
    build: ./mock-server
    ports:
      - '3000:3000'
