services:
  frontend:
    container_name: money-management-frontend
    build: ./source/frontend
    ports:
      - '4200:80'
    depends_on:
      - backend

  backend:
    container_name: money-management-backend
    build: ./source/backend
    environment:
      - 'ConnectionStrings__Postgres=Server=host.docker.internal;Port=5432;Database=mm-dev;User Id=postgres;Password=DrOid-R2D2'
      - 'ExchangeServerBaseUrl=http://frankfurter:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frankfurter:
    container_name: money-management-exchange
    image: lineofflight/frankfurter
