FROM node:18-alpine as build
WORKDIR /usr/local/app
COPY . .
RUN npm ci
RUN npm run build

FROM node:18-alpine
COPY --from=build /usr/local/app/build/bundle.js /usr/local/mock-server/bundle.js
CMD [ "node", "/usr/local/mock-server/bundle.js" ]
EXPOSE 3000
