name: App Build

run-name: App Build @${{ github.sha }}

on:
  workflow_run:
    workflows: [Create App Version Label]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/**
      - mock-server/**
      - '*.md'

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    name: App Build
    uses: ./.github/workflows/build.yml
    with:
      node-version: 16.x
      dist-path: dist/money-management
      artifact-prefix: dist
