name: Backend Build

run-name: Backend Build @${{ github.sha }}

on:
  workflow_run:
    workflows: [Increment version for 'Backend']
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
      - release/*
    paths:
      - source/backend/**

jobs:
  label_check:
    if: ${{ github.event_name == 'pull_request' }}
    name: Pull Request Label Checker
    uses: sergey-koryshev/build-system/.github/workflows/pr-label-checker.yml@version-helper-v1.2.0
    with:
      version-configuration-path: source/backend/version-configuration.json
      scripts-ref: version-helper-v1.2.0
  debug-build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    name: Backend Debug Build
    uses: ./.github/workflows/dotnet-build.yml
    with:
      root-path: source/backend
      dotnet-version: 7.0.x
      solution-path: Backend.sln
      build-configuration: Debug
      test-project-path: Backend.Tests/Backend.Tests.csproj
  release-build:
    if: ${{ github.event_name != 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    name: Backend Release Build
    uses: ./.github/workflows/dotnet-build.yml
    with:
      root-path: source/backend
      dotnet-version: 7.0.x
      solution-path: Backend.sln
      build-configuration: Release
      test-project-path: Backend.Tests/Backend.Tests.csproj
