on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      root-path:
        required: false
        type: string
      dist-path:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      node-version: 16.x
    steps:
      - uses: actions/checkout@v3
      - name: Set root
        if: ${{ inputs.root-path != '' }}
        run: |
          cd $ROOT_PATH
          echo Root directory set to $(pwd)
        env:
          ROOT_PATH: ${{ inputs.root-path }}
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Get current version
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          version=$(npm pkg get version --workspaces=false | tr -d \")
          echo "version=$version" >> "$GITHUB_ENV"
          nodeVersion=$(node -v)
          echo "nodeVersion=$nodeVersion" >> "$GITHUB_ENV"
      - name: Publish Artifacts
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: 'dist-${{ env.version }}-node-${{ env.nodeVersion }}'
          path: ${{ inputs.dist-path }}
