on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      dist-path:
        required: true
        type: string
      artifact-prefix:
        required: true
        type: string
      root-path:
        required: false
        type: string
        default: .
      run-lint:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.root-path }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install packages
        run: npm ci
      - name: Run lint
        if: ${{ inputs.run-lint == true }}
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Get current version
        run: |
          version=$(npm pkg get version --workspaces=false | tr -d \")
          echo "version=$version" >> "$GITHUB_ENV"
          nodeVersion=$(node -v)
          echo "nodeVersion=$nodeVersion" >> "$GITHUB_ENV"
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: '${{ inputs.artifact-prefix }}-${{ env.version }}-node-${{ env.nodeVersion }}'
          path: ${{ inputs.root-path }}/${{ inputs.dist-path }}
