name: Increment version for 'Backend'

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - source/backend/**

jobs:
  create_label:
    name: Increment version
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Increment Version
        uses: sergey-koryshev/bump-version@6d176fd6306315acba741862476574d3e49f8f7a
        with:
          app-name: backend
          root-path: source/backend
          project-type: Custom
          posh-custom-module-path: build/WebApiIncrementVersionHelper.psm1
          version-configuration-path: source/backend/version-configuration.json
