name: Create MockServer Version Label

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - mock-server/**

jobs:
  create_label:
    name: Create App Version Label
    uses: ./.github/workflows/create-label.yml
    with:
      app-name: mock-server
      repo-token: ${{ secrets.REPO_PAT }}
      root-path: mock-server
