name: Create MockServer Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - source/mock-server/**

jobs:
  create_label:
    name: Create App Version Label
    uses: ./.github/workflows/create-label.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      app-name: mock-server
      skip-tag: true
      root-path: source/mock-server
