name: Create Backend Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - source/backend/**

jobs:
  create_label:
    name: Create Version Label
    uses: sergey-koryshev/build-system/.github/workflows/create-version-label.yml@version-helper-v1.2.1
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      app-name: backend
      root-path: source/backend
      project-type: Custom
      posh-custom-module-path: ${{ github.workspace }}/build/WebApiIncrementVersionHelper.psm1
      version-configuration-path: source/backend/version-configuration.json
      scripts-ref: version-helper-v1.2.1
