name: Create Frontend Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - source/frontend/**

jobs:
  create_label:
    name: Create Version Label
    uses: sergey-koryshev/build-system/.github/workflows/create-version-label.yml@version-helper-v1.2.0
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      app-name: frontend
      root-path: source/frontend
      project-type: Node
      version-configuration-path: source/frontend/version-configuration.json
      scripts-ref: version-helper-v1.2.0
