name: Increment version for 'Frontend'

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - epic/**
    paths:
      - source/frontend/**

jobs:
  create_label:
    name: Increment version
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      ROOT_PATH: source/frontend
      PRODUCT_VERSION_FILE: version.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Get suffix
        id: suffix
        if: ${{ startsWith(github.ref, 'refs/heads/epic/') }}
        shell: pwsh
        run: |
          $epicBranchName = "${{ github.ref_name }}"
          "suffix=$($epicBranchName -replace '^epic/', '')" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Increment Version
        uses: sergey-koryshev/bump-version@v1.2.1
        with:
          app-name: frontend
          root-path: ${{ env.ROOT_PATH }}
          project-type: Node
          version-configuration-path: ${{ env.ROOT_PATH }}/${{ case(github.ref == 'refs/heads/master', 'version-configuration.json', 'epic-version-configuration.json') }}
          default-increment-part: ${{ case(github.ref == 'refs/heads/master', 'Patch', 'Suffix') }}
          suffix: ${{ steps.suffix.outputs.suffix }}

      - name: Propagate DEV product version to frontend
        shell: pwsh
        run: |
          . build/PropagateFrontendProductVersion.ps1 -ProjectRootPath $env:ROOT_PATH -ProductVersionFile $env:PRODUCT_VERSION_FILE
