name: Create MockServer Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - source/mock-server/**

jobs:
  create_label:
    name: Create Version Label
    uses: sergey-koryshev/build-system/.github/workflows/create-version-label.yml@version-helper-v1.2.0
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      app-name: mock-server
      root-path: source/mock-server
      project-type: Node
      version-configuration-path: source/mock-server/version-configuration.json
      scripts-ref: version-helper-v1.2.0
