name: Increment version for 'Frontend'

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - source/frontend/**

jobs:
  create_label:
    name: Increment version
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      ROOT_PATH: source/frontend
      PRODUCT_VERSION_FILE: version.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Increment Version
        uses: sergey-koryshev/bump-version@v1.0.4
        with:
          app-name: frontend
          root-path: ${{ env.ROOT_PATH }}
          project-type: Node
          version-configuration-path: ${{ env.ROOT_PATH }}/version-configuration.json

      - name: Propagate DEV product version to frontend
        shell: pwsh
        run: |
          . build/PropagateFrontendProductVersion.ps1 -ProjectRootPath $env:ROOT_PATH -ProductVersionFile $env:PRODUCT_VERSION_FILE
