name: Create Frontend Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - sources/frontend/**

jobs:
  create_label:
    name: Create App Version Label
    uses: ./.github/workflows/create-label.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      app-name: frontend
      root-path: sources/frontend
