name: Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      solution-path:
        required: true
        type: string
      root-path:
        required: false
        type: string
        default: .
      build-configuration:
        required: false
        type: string
        default: "Debug"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.root-path }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Build
        run: dotnet build ${{ inputs.solution-path }} -c ${{ inputs.build-configuration }}
