name: Frontend Build

run-name: Frontend Build @${{ github.sha }}

on:
  workflow_run:
    workflows: [Create Frontend Version Label]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - source/frontend/**

jobs:
  dev-build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    name: Frontend Dev Build
    uses: ./.github/workflows/node-build.yml
    with:
      node-version: 16.x
      root-path: source/frontend
      dist-path: dist/money-management
      artifact-prefix: frontend-dev
      build-command: "npm run build:dev"
  prod-build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    name: Frontend Prod Build
    uses: ./.github/workflows/node-build.yml
    with:
      node-version: 16.x
      root-path: source/frontend
      dist-path: dist/money-management
      artifact-prefix: frontend-prod
      build-command: "npm run build"
