name: Check Labels

on:
  pull_request:
    branches:
      - master

jobs:
  label_checker:
    name: Check Labels
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - name: Check Labels in PR
        shell: pwsh
        run: |
          $splitRepositoryName = "${{ github.repository }}" -split "/"
          if ($splitRepositoryName.Length -ne 2) {
            throw "Repository name can't be parsed: ${{ github.repository }}"
          }
          .\build\scripts\Get-Labels.ps1 -PullRequestId ${{ github.event.pull_request.number }} -Owner $splitRepositoryName[0] -Repository $splitRepositoryName[1] | Out-Null