name: Mock Server Build

run-name: Mock Server Build @${{ github.sha }}

on:
  workflow_run:
    workflows: [Create MockServer Version Label]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - mock-server/**

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    name: Mock Server Build
    uses: ./.github/workflows/build.yml
    with:
      node-version: 16.x
      root-path: mock-server
      dist-path: build
      artifact-prefix: mock-server
      run-lint: true
