name: Mock Server Build

run-name: Mock Server Build @${{ github.sha }}

on:
  workflow_run:
    workflows: [Create MockServer Version Label]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - source/mock-server/**

jobs:
  label_check:
    if: ${{ github.event_name == 'pull_request' }}
    name: Pull Request Label Checker
    uses: sergey-koryshev/build-system/.github/workflows/pr-label-checker.yml@version-helper-v1.2.0
    with:
      version-configuration-path: source/mock-server/version-configuration.json
      scripts-ref: version-helper-v1.2.0
  dev-build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    name: Mock Server Dev Build
    uses: ./.github/workflows/node-build.yml
    with:
      node-version: 16.x
      root-path: source/mock-server
      dist-path: build
      artifact-prefix: mock-server-dev
      run-lint: true
      build-command: "npm run build:dev"
  prod-build:
    if: ${{ github.event_name != 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    name: Mock Server Prod Build
    uses: ./.github/workflows/node-build.yml
    with:
      node-version: 16.x
      root-path: source/mock-server
      dist-path: build
      artifact-prefix: mock-server-prod
      run-lint: true
      build-command: "npm run build"
