name: Release Branch Checker

run-name: Check Branch ${{ github.ref }}

on:
  create:

jobs:
  release-workflow:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    name: Kick off Release Workflow for Branch ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: Sending event 'release_branch_created'
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'release_branch_created'
            })